### PR TITLE
Add Raspberry Pi and OS X suport

### LINKED ISSUE #2: Adding Raspberry Pi (1) support
Hey, I followed the instructions in the readme to build the config.h file for my raspberry pi (and fleshed it out a bit): https://github.com/nfriedly/node-opus/commit/0ad226a74801f12e8f7b9b59686158c4866dde26

But, when I try to install from my repo, I get the following:

```
pi@raspberrypi ~/nodeplayer $ npm install https://github.com/nfriedly/node-opus
npm ERR! Linux 3.18.12+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/nfriedly/node-opus"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: node-opus@0.1.2
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm
```

Presumably one of the .gyp files needs to be updated, but I'm not sure which / how. Can you give me any pointers there?

### PR DESCRIPTION
**Pull request by nfriedly**
Fixes https://github.com/Rantanen/node-opus/issues/2

Sorry that github thinks 360 files were changed. In reality, it was only 4 files. But I merged your deps change instead of rebasing... so git is going nuts.

### CODE REVIEW

**Comment by nfriedly** [comment]
If you really want the clean history, I can create a new branch and do some cherry-picking

**Comment by Rantanen** [comment]
Could you do that? :)

Or just `rebase -i` this one to the master and skip my commits.

I don't really care about the history, but I'd like to have a glance at the changes which is painful with the 29672 changed lines. :)

(I think there was something in the README.md for example that was still referencing `git submodule`, which is what I got rid of to make this work. So that could be removed as well)

**Comment by nfriedly** [comment]
Nice... I feel like a freaking git ninja right now.

**Comment by Rantanen** [comment]
Oh! That was all of it! I was still waiting for the other commits, didn't realize you squashed them to just two. Nice! :)

**Comment by nfriedly** [comment]
Yea, I just went a little nuts when I realized exactly how powerful `git rebase -i` is :D

**Comment by Rantanen** [comment]
Thanks! Removed the `git submodule` commands from the `README.md` and pushed to npm!

(And yes, it is! <3)

**Comment by nfriedly** [comment]
Whoot! Thanks for staying up late(ish) and hammering this out with me!

**Comment by Rantanen** [comment]
No problem! Always happy with incoming PRs.

.. Although I did miss the chance to delay that last commit of mine by 30 seconds to make it count for today's Streak: `Wed May 6 23:59:35 2015 +0300`. Damn you, Github for tracking such statistics! :)

**Pull request merged**
